
DATE= `date +%m%d`

TARFILE = PAS2006.$(DATE).src.tar

tar:
	/bin/tar cf $(TARFILE) KUN/*.[ch]pp KUN/*.h KUN/[Mm]akefile* KUN/*.cfg KUN/*.acl KUN/*.txt emul/ lib/*.[ch]pp tools/*.cpp tools/*.h tools/[Mm]ake* monitor/

